package cn.gydev.challenge.service;

import jakarta.servlet.http.HttpServletRequest;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.springframework.boot.json.JsonParser;
import org.springframework.boot.json.JsonParserFactory;
import org.springframework.stereotype.Service;

/**
 * Demo risk challenge service for browser-side token generation and server-side validation.
 */
@Service
public class RiskChallengeService {

    private static final long CHALLENGE_TTL_MS = 120_000L;
    private static final long TOKEN_MAX_AGE_MS = 120_000L;
    private static final long POW_MAX_AGE_MS = 60_000L;
    private static final int HEADER_HASH_PREFIX_LEN = 12;
    private static final int TOKEN_VERSION = 1;
    private static final int PROOF_TOKEN_VERSION = 1;
    private static final int POW_DIFFICULTY = 4;
    private static final String HMAC_ALGO = "HmacSHA256";
    private static final String POW_ALGO = "sha256-prefix-zero";

    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    private static final JsonParser JSON_PARSER = JsonParserFactory.getJsonParser();

    private final ConcurrentMap<String, ChallengeSession> sessions = new ConcurrentHashMap<>();
    private final Set<String> usedRiskNonces = ConcurrentHashMap.newKeySet();
    private final Set<String> usedProofNonces = ConcurrentHashMap.newKeySet();
    private final TlsClassifierService tlsClassifierService;

    public RiskChallengeService(TlsClassifierService tlsClassifierService) {
        this.tlsClassifierService = tlsClassifierService;
    }

    /**
     * Initializes a short-lived challenge for frontend token creation.
     *
     * @return challenge details
     */
    public Map<String, Object> initChallenge() {
        cleanupExpired();

        String challengeId = randomHex(16);
        String sessionKey = randomHex(32);
        long now = System.currentTimeMillis();
        long expiresAt = now + CHALLENGE_TTL_MS;

        sessions.put(challengeId, new ChallengeSession(challengeId, sessionKey, expiresAt));

        Map<String, Object> publicParams = new LinkedHashMap<>();
        publicParams.put("tokenVersion", TOKEN_VERSION);
        publicParams.put("maxAgeMs", TOKEN_MAX_AGE_MS);
        publicParams.put("fpHashFormat", "headerPrefix:deviceHash");
        Map<String, Object> powParams = new LinkedHashMap<>();
        powParams.put("algo", POW_ALGO);
        powParams.put("difficulty", POW_DIFFICULTY);
        powParams.put("maxAgeMs", POW_MAX_AGE_MS);

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("challengeId", challengeId);
        result.put("expiresAt", Instant.ofEpochMilli(expiresAt).toString());
        result.put("salt", sessionKey);
        result.put("publicParams", publicParams);
        result.put("pow", powParams);
        return result;
    }

    /**
     * Validates risk token and decides whether to accept the request.
     *
     * @param content business content
     * @param riskToken token generated by frontend
     * @param request HTTP request
     * @return decision payload
     */
    public Map<String, Object> validateSubmission(
            String content,
            String riskToken,
            String proofToken,
            HttpServletRequest request) {
        return validateSubmissionInternal(content, riskToken, proofToken, request, true);
    }

    /**
     * Validates gydev token but skips sentinel proof validation.
     *
     * @param content business content
     * @param riskToken token generated by frontend
     * @param request HTTP request
     * @return decision payload
     */
    public Map<String, Object> validateSubmissionWithoutPow(
            String content,
            String riskToken,
            HttpServletRequest request) {
        return validateSubmissionInternal(content, riskToken, "", request, false);
    }

    private Map<String, Object> validateSubmissionInternal(
            String content,
            String riskToken,
            String proofToken,
            HttpServletRequest request,
            boolean enforcePow) {
        cleanupExpired();

        if (content == null || content.isBlank()) {
            return decision(false, false, "high", "Content is empty", 0L);
        }
        if (riskToken == null || riskToken.isBlank()) {
            return decision(false, false, "high", "Risk token is missing", 0L);
        }
        if (enforcePow && (proofToken == null || proofToken.isBlank())) {
            return decision(false, false, "high", "pow_missing", 0L);
        }

        TokenPayload payload;
        try {
            payload = parseTokenPayload(riskToken);
        } catch (Exception ex) {
            return decision(false, false, "high", "Risk token format is invalid", 0L);
        }

        if (payload.v != TOKEN_VERSION) {
            return decision(false, false, "high", "Unsupported token version", 0L);
        }

        long now = System.currentTimeMillis();
        long ageMs = Math.max(0L, now - payload.ts);
        if (ageMs > TOKEN_MAX_AGE_MS) {
            return decision(false, false, "high", "Risk token is expired", ageMs);
        }

        ChallengeSession session = sessions.get(payload.challengeId);
        if (session == null || session.expiresAtMs < now) {
            return decision(false, false, "high", "Challenge is missing or expired", ageMs);
        }

        String nonceKey = payload.challengeId + ":" + payload.nonce;
        if (!usedRiskNonces.add(nonceKey)) {
            return decision(false, false, "high", "Risk token replay detected", ageMs);
        }

        if (!verifyFpWeakBinding(payload.fpHash, request)) {
            return decision(false, false, "high", "Fingerprint/header weak binding mismatch", ageMs);
        }

        String signingBase = signingBase(payload);
        String expectedSig = hmacHex(session.sessionKey, signingBase);
        if (!Objects.equals(expectedSig, payload.sig)) {
            return decision(false, false, "high", "Risk token signature mismatch", ageMs);
        }

        boolean powVerified = !enforcePow;
        if (enforcePow) {
            ProofTokenPayload proof;
            try {
                proof = parseProofTokenPayload(proofToken);
            } catch (Exception ex) {
                return decision(false, false, "high", "pow_invalid", ageMs);
            }

            if (proof.v != PROOF_TOKEN_VERSION) {
                return decision(false, false, "high", "pow_invalid", ageMs);
            }
            if (!payload.challengeId.equals(proof.challengeId) || !payload.nonce.equals(proof.riskNonce)) {
                return decision(false, false, "high", "pow_invalid", ageMs);
            }
            long proofAgeMs = Math.max(0L, now - proof.ts);
            if (proofAgeMs > POW_MAX_AGE_MS) {
                return decision(false, false, "high", "pow_expired", ageMs);
            }
            String proofNonceKey = proof.challengeId + ":" + proof.proofNonce;
            if (!usedProofNonces.add(proofNonceKey)) {
                return decision(false, false, "high", "pow_replay", ageMs);
            }
            String expectedHash = sha256Hex(proof.challengeId + "|" + proof.riskNonce + "|" + proof.proofNonce + "|" + proof.ts);
            if (!hasLeadingZeros(expectedHash, POW_DIFFICULTY) || !expectedHash.equals(proof.hash)) {
                return decision(false, false, "high", "pow_invalid", ageMs);
            }
            powVerified = true;
        }

        String riskLevel = "low";
        String reason = "Challenge passed";

        @SuppressWarnings("unchecked")
        Map<String, Object> tls = (Map<String, Object>) tlsClassifierService.classify(request);
        String tlsType = String.valueOf(tls.getOrDefault("type", "unknown"));

        if ("program".equals(tlsType)) {
            riskLevel = "high";
            reason = "Challenge passed but TLS classifier indicates program client";
        } else if (payload.behScore < 35) {
            riskLevel = "medium";
            reason = "Challenge passed with low behavior score";
        }

        Map<String, Object> result = decision(true, powVerified, riskLevel, reason, ageMs);
        result.put("tlsType", tlsType);
        return result;
    }

    private Map<String, Object> decision(boolean accepted, boolean powVerified, String riskLevel, String reason, long tokenAgeMs) {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("accepted", accepted);
        result.put("powVerified", powVerified);
        result.put("riskLevel", riskLevel);
        result.put("reason", reason);
        result.put("tokenAgeMs", tokenAgeMs);
        return result;
    }

    private boolean verifyFpWeakBinding(String fpHash, HttpServletRequest request) {
        if (fpHash == null || fpHash.isBlank() || !fpHash.contains(":")) {
            return false;
        }
        String[] parts = fpHash.split(":", 2);
        String prefix = parts[0];

        String ua = header(request, "User-Agent");
        String lang = canonicalPrimaryLanguage(header(request, "Accept-Language"));
        String secChUa = canonicalSecChUa(header(request, "Sec-CH-UA"));
        String expected = sha256Hex(ua + "|" + lang + "|" + secChUa).substring(0, HEADER_HASH_PREFIX_LEN);
        return expected.equals(prefix);
    }

    private String canonicalPrimaryLanguage(String acceptLanguage) {
        if (acceptLanguage == null || acceptLanguage.isBlank()) {
            return "";
        }
        String first = acceptLanguage.split(",")[0].trim();
        int qIdx = first.indexOf(";q=");
        if (qIdx > 0) {
            return first.substring(0, qIdx).trim();
        }
        return first;
    }

    private String canonicalSecChUa(String secChUaHeader) {
        if (secChUaHeader == null || secChUaHeader.isBlank()) {
            return "";
        }
        List<String> items = new ArrayList<>();
        String[] parts = secChUaHeader.split(",");
        for (String part : parts) {
            String p = part.trim();
            int q1 = p.indexOf('"');
            int q2 = p.indexOf('"', q1 + 1);
            int vPos = p.indexOf(";v=");
            if (q1 >= 0 && q2 > q1 && vPos > q2) {
                String brand = p.substring(q1 + 1, q2);
                String versionRaw = p.substring(vPos + 3).trim();
                String version = stripQuotes(versionRaw);
                items.add(brand + "/" + version);
            }
        }
        return String.join(",", items);
    }

    private String stripQuotes(String input) {
        if (input == null || input.isBlank()) {
            return "";
        }
        String out = input.trim();
        if (out.length() >= 2 && out.startsWith("\"") && out.endsWith("\"")) {
            return out.substring(1, out.length() - 1);
        }
        return out;
    }

    private TokenPayload parseTokenPayload(String riskToken) {
        String json = new String(Base64.getUrlDecoder().decode(riskToken), StandardCharsets.UTF_8);
        Map<String, Object> map = JSON_PARSER.parseMap(json);
        int v = intValue(map.get("v"));
        long ts = longValue(map.get("ts"));
        String challengeId = stringValue(map.get("challengeId"));
        String nonce = stringValue(map.get("nonce"));
        String fpHash = stringValue(map.get("fpHash"));
        int behScore = intValue(map.get("behScore"));
        String sig = stringValue(map.get("sig")).toLowerCase(Locale.ROOT);
        return new TokenPayload(v, ts, challengeId, nonce, fpHash, behScore, sig);
    }

    private ProofTokenPayload parseProofTokenPayload(String proofToken) {
        String json = new String(Base64.getUrlDecoder().decode(proofToken), StandardCharsets.UTF_8);
        Map<String, Object> map = JSON_PARSER.parseMap(json);
        int v = intValue(map.get("v"));
        String challengeId = stringValue(map.get("challengeId"));
        String riskNonce = stringValue(map.get("riskNonce"));
        String proofNonce = stringValue(map.get("proofNonce"));
        long ts = longValue(map.get("ts"));
        String hash = stringValue(map.get("hash")).toLowerCase(Locale.ROOT);
        return new ProofTokenPayload(v, challengeId, riskNonce, proofNonce, ts, hash);
    }

    private String signingBase(TokenPayload payload) {
        return payload.v + "|" + payload.ts + "|" + payload.challengeId + "|" + payload.nonce + "|"
                + payload.fpHash + "|" + payload.behScore;
    }

    private int intValue(Object value) {
        return Integer.parseInt(String.valueOf(value));
    }

    private long longValue(Object value) {
        return Long.parseLong(String.valueOf(value));
    }

    private String stringValue(Object value) {
        return value == null ? "" : String.valueOf(value).trim();
    }

    private String header(HttpServletRequest request, String name) {
        String value = request.getHeader(name);
        return value == null ? "" : value.trim();
    }

    private String hmacHex(String secret, String data) {
        try {
            Mac mac = Mac.getInstance(HMAC_ALGO);
            mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8), HMAC_ALGO));
            return toHex(mac.doFinal(data.getBytes(StandardCharsets.UTF_8)));
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to calculate HMAC", ex);
        }
    }

    private String sha256Hex(String data) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            return toHex(digest.digest(data.getBytes(StandardCharsets.UTF_8)));
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to calculate sha256", ex);
        }
    }

    private String toHex(byte[] bytes) {
        StringBuilder sb = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }

    private String randomHex(int byteLength) {
        byte[] bytes = new byte[byteLength];
        SECURE_RANDOM.nextBytes(bytes);
        return toHex(bytes);
    }

    private void cleanupExpired() {
        long now = System.currentTimeMillis();
        sessions.values().removeIf(s -> s.expiresAtMs < now);
    }

    private boolean hasLeadingZeros(String hex, int difficulty) {
        if (hex == null || hex.length() < difficulty) {
            return false;
        }
        for (int i = 0; i < difficulty; i++) {
            if (hex.charAt(i) != '0') {
                return false;
            }
        }
        return true;
    }

    private record ChallengeSession(String challengeId, String sessionKey, long expiresAtMs) {
    }

    private record TokenPayload(
            int v,
            long ts,
            String challengeId,
            String nonce,
            String fpHash,
            int behScore,
            String sig
    ) {
    }

    private record ProofTokenPayload(
            int v,
            String challengeId,
            String riskNonce,
            String proofNonce,
            long ts,
            String hash
    ) {
    }
}
